# command to install dependencies
install:
  - "pip install selenium"
  - "pip install behave"
  - "pip install jsonpath-rw"

# command to run tests
script: 
    - make test
    - cd tests/behave
    - source bin/activate
    - behave

after_success:
  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kshefchek@gmail.com
