language: javascript

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "uname -a"
  - "gcc --version"
  - "lsb_release -a"
  - "rm -r ~/.node-gyp"
  - "npm cache clean -f"
  - "nvm install 4.2.2"
  - "nvm use 4.2.2"
  - "npm version"
  - "npm install -g npm@3.4.0"
  - "npm version"
  - "which npm"

# command to install dependencies
install:
  - "# rm -rf node_modules/"
  - "./install.sh"
  - "sudo pip install selenium"
  - "sudo pip install behave"
  - "sudo pip install jsonpath-rw"

before_script:
  - "export DISPLAY=:99.0"
  - "# ./start-server.sh &"
  - "npm run build"
  - "npm run bstart &"
  - "sleep 25"

after_success:
  - "cat ./webdriver.log"
  - "cat ../../start-server.log"

after_failure:
  - "cat ./webdriver.log"
  - "cat ../../start-server.log"

# command to run tests
script:
  - "# ps auwx|grep webapp_launcher.js"
  - "make test"
  - "cd tests/behave"
  - "# ps auwx|grep webapp_launcher.js"
  - "# curl -v http://localhost:8080"
  - "# curl -v http://localhost:8080/disease/DOID:3044.json"
  - "TARGET=http://localhost:8080 behave"

# whitelist
branches:
  only:
    - master
    - production
    - stage

notifications:
  email:
    - kshefchek@gmail.com
