language: javascript

# command to install dependencies
install:
  - "./install.sh"

# command to run tests
script: 
  - "make test"
  - "sudo pip install selenium"
  - "sudo pip install behave"
  - "sudo pip install jsonpath-rw"
  - "./start-server.sh"
  - "cd tests/behave"
  - "behave"

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kshefchek@gmail.com
