language: javascript

# command to install dependencies
install:
  - "./install.sh"
  - "sudo pip install selenium"
  - "sudo pip install behave"
  - "sudo pip install jsonpath-rw"

before_script:
  - "./start-server.sh &"
  - "sleep 25"

# command to run tests
script: 
  - "make test"
  - "cd tests/behave"
  - "TARGET=http://localhost:8080 BROWSER=phantomjs behave"

# whitelist
branches:
  only:
    - master
    - production

notifications:
  email:
    - kshefchek@gmail.com
