language: javascript

# command to install dependencies
install:
  - "./install.sh"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to run tests
script: 
  - "make test"
  - "sudo pip install selenium"
  - "sudo pip install behave"
  - "sudo pip install jsonpath-rw"
  - "cd tests/behave"
  - "./start-server.sh &"
  - "sleep 10"
  - "TARGET=http://localhost:8080 behave"

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kshefchek@gmail.com
